DATASET:
  ROOT: "/media/shuo/MyDrive/data/brain/qc"
  QC: True
  DOWNLOAD: True
#METHOD:
#  ALGORITHM: "LR"
OUTPUT:
  ROOT: "/media/shuo/MyDrive/data/brain/qc"
  OUT_PATH: "/media/shuo/MyDrive/data/brain/qc/ABIDE_pcp/cpac/filt_noglobal/"
