DATASET:
  ROOT: "D:/ML_data/brain/qc"
#  ROOT: "/media/shuo/MyDrive/data/brain/qc"
  QC: True
  DOWNLOAD: False
#METHOD:
#  ALGORITHM: "LR"
OUTPUT:
  ROOT: "D:/ML_data/brain/qc"
  OUT_PATH: "D:/ML_data/brain/qc/ABIDE_pcp/cpac/filt_noglobal/"
#  ROOT: "/media/shuo/MyDrive/data/brain/qc"
#  OUT_PATH: "/media/shuo/MyDrive/data/brain/qc/ABIDE_pcp/cpac/filt_noglobal/"
